<?php
 $title = NEWSLETTER_SUBSCRIPTION;
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(!empty($this->message)){
    ?>
    <div class="alert alert-info"><?php echo $this->message; ?></div>
    <?php
}
$form->setAttribute('action', '');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'newsletter_subscription');
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <label class="control-label col-sm-2" for="inputEmail"><?php echo $this->translate('Email'); ?><em>*</em></label>
    <div class="col-sm-3">
        <?php
		if($this->message){
            echo $this->formRow($form->get('email')->setValue(''));
		}else{
			echo $this->formRow($form->get('email'));
		}
        ?>
		<label id="emailExists" class="error" style="display: none;">you are already subscribed.</label>
	</div>
</div>
<div class="form-group">
    <label class="control-label col-sm-2"></label>
    <div class="col-sm-3">
		<?php
		echo $this->formSubmit($form->get('submit'));
		?>
    </div>
</div>
<?php
echo $this->form()->closeTag();