<script>
	var TB_WIDTH = 350,
        TB_HEIGHT = 200; //Set the new width and height dimensions here..
	$("#TB_window").css({
        marginLeft: '-' + parseInt((TB_WIDTH / 2), 10) + 'px',
        width: TB_WIDTH + 'px',
        height: TB_HEIGHT + 'px',
        marginTop: '-' + parseInt((TB_HEIGHT / 2), 10) + 'px'
	});

	jQuery("#yes").click(function(){
		url = baseUrl+'/manage-subscribers/deletesubscriber/pid/'+jQuery("#confirm_id").val();
		location.href = url;
	});

	//Function for remove confirm box
	jQuery("#no").click(function(){
	tb_remove();
	});
</script>
<div id="msgBlock">
	<p>Are you sure, you want to delete this email subscriber?</p>
	<div class="form-button">
	  <input type="hidden" value="<?php echo $this->id;?>" id="confirm_id"/>
	  <input type="button"  class="button blue" value="Yes" id="yes" name="yes">
	  <input type="button" class="button blue" value="No" id="no" name="no">
	</div>
</div>