<?php
 $title = MANAGE_EMAIL_SUBSCRIBER;
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if(!empty($this->message)){
    ?>
    <div class="alert alert-info"><?php echo $this->message; ?></div>
    <?php
}
?>
<?php if($this->showSearch){ ?>
		<form action="<?php echo $this->url('manage-subscribers',array('action'=>'index')); ?>" name='searchGridForm' id="searchGridForm" method="get" >
		  <label class="left">Search:
		   <input type="text" name="search">
		  </label>
		  <input class="button" type="submit" value="Search"/>
		</form>
<?php }?>
 <table class="table">
 <tr>
    <th>Sr.N.</th>
	<?php
	foreach($fields as $field){
		if($field['visible']==1){
			?>
			<th><?php
			if($field['sorting']==1){
				?>
				<a href="<?php echo $this->url('manage-subscribers',array('action'=>'index')).'?sort='.$field['fieldName'].'&order='.$defaultSortOrder; ?>">
					<?php echo $field['label']; ?>
				</a>
				<?php
			}else{
				echo $field['label'];
			}
			?></th>
			<?php
		}
	}
	?>
	 <th>Action</th>
 </tr>
 <?php
 if(count($emailSubscribers)>0){
 $counter=$this->serialNumber;
 foreach ($emailSubscribers as $subscriber){  ?>
 <tr>
    <td><?php echo $counter;?></td>
    <td><?php echo $this->escapeHtml($subscriber->email_id);?></td>
    <td><?php echo $this->escapeHtml($subscriber->subscription_date);?></td>
    <td>
        <a class="thickbox" href="<?php echo $this->url('manage-subscribers',
             array('action'=>'deletesubscriber', 'id' => $subscriber->id));?>">Delete</a>
    </td>
 </tr>
 <?php
 $counter++;
 }
 ?>
 </table>
 <?php
 }else{
    ?>
  <div class="alert alert-info"><?php echo "No Record Found."; ?></div>
    <?php
 }
 ?>
 <?php
 if(count($this->emailSubscribers)>1){
echo $this->paginationControl(
    $this->emailSubscribers,
    'sliding',
    // The partial to use to render the control
    array('partial/paginator.phtml', 'Newsletter'),
    //The route to link to when a user clicks a control link
    array(
        'route' => 'manage-subscribers'
    )
);
 }